name: project-check

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - name: Run linter
        run: |
          pip install flake8
          make lint
      - name: Run pytest
        run: |
          pip install pytest
          make test
      - name: Run mypy
        run: |
          pip install mypy
          make typing